/**
 * Recorded checksums and sizes for every catalog file.
 *
 * GENERATED by `npm run verify:catalog` — do not edit by hand. The script
 * downloads each file once and records what it actually received, keyed by
 * URL.
 *
 * This is a generated data file rather than values inlined in the catalog so
 * that regenerating it never rewrites hand-written source, and so two entries
 * can share a file list without becoming indistinguishable to the recorder.
 *
 * An unlisted URL means "not yet verified": `ModelManager` then falls back to
 * checking size alone, which is why an entry with no record still installs
 * but is not integrity-checked.
 */
export type ModelHash = { sha256: string; sizeBytes: number }

export const MODEL_HASHES: Record<string, ModelHash> = {}
