/**
 * Recorded checksums and sizes for every catalog file.
 *
 * GENERATED by `npm run verify:catalog` — do not edit by hand. The script
 * downloads each file once and records what it actually received.
 *
 * Keyed by `<entry id>/<file name>` rather than by URL, so changing where a
 * file is fetched from keeps its recorded hash and fails the checksum loudly.
 * A URL key would quietly drop the record and fall back to checking size
 * alone — the wrong failure for the thing that exists to catch tampering.
 *
 * This is a generated data file rather than values inlined in the catalog so
 * that regenerating it never rewrites hand-written source, and so two entries
 * can share a file list without becoming indistinguishable to the recorder.
 */
export type ModelHash = { sha256: string; sizeBytes: number }

export const MODEL_HASHES: Record<string, ModelHash> = {
  'moonshine-base-en/config.json': {
    sha256: 'fab7241d1e9fc6c2370c4c6dfb5da79bb54d67ed9ab6b507ac51d29d2abe01d1',
    sizeBytes: 922
  },
  'moonshine-base-en/generation_config.json': {
    sha256: 'f9b3f711b57be7def2e50a8942f64f36ee0a55fad5b84ff93a687b6c5bcc1d44',
    sizeBytes: 147
  },
  'moonshine-base-en/onnx/decoder_model_merged.onnx': {
    sha256: '58778763ca8438963190244d6b26572bdca2cedec56a4b91e828f3f2d69ef3c5',
    sizeBytes: 166211345
  },
  'moonshine-base-en/onnx/encoder_model.onnx': {
    sha256: '153e128e7abd64a74ee47f2c3f585c3171c4d46cbb368b032827934c4e01e779',
    sizeBytes: 80818781
  },
  'moonshine-base-en/preprocessor_config.json': {
    sha256: 'fa43a7017ef85cd1d0fba0d9aae77c8adb16990ae6f11115631f41ec5d8aa679',
    sizeBytes: 128
  },
  'moonshine-base-en/tokenizer_config.json': {
    sha256: 'edaee394565d428ea98a663ae7209cdcfeefc5585c42d7a570ff7c986df2cd15',
    sizeBytes: 135735
  },
  'moonshine-base-en/tokenizer.json': {
    sha256: '7b913404bdd039af4756783218af4440bc07fb7d6d8258d677e34f95b3ec416f',
    sizeBytes: 3761754
  },
  'silero-vad/silero_vad.onnx': {
    sha256: 'a4a068cd6cf1ea8355b84327595838ca748ec29a25bc91fc82e6c299ccdc5808',
    sizeBytes: 2243022
  },
  'whisper-base-en/config.json': {
    sha256: 'c8a0de5ed8a083565a4319db29d0c210fda35b4d6076c2d711cae53ae00f3cb1',
    sizeBytes: 2197
  },
  'whisper-base-en/generation_config.json': {
    sha256: '3479b1f44a07e41db799e22599222fee5816738036def94a39841cb9cdbb4120',
    sizeBytes: 1556
  },
  'whisper-base-en/onnx/decoder_model_merged.onnx': {
    sha256: 'e98d168e2d82e7fb4fabcceabc4ec8ef986c864ddd5fc66ff3ef1410cd2c5cff',
    sizeBytes: 208519480
  },
  'whisper-base-en/onnx/encoder_model.onnx': {
    sha256: '1cc86302d480b061452d348638064383ab41b6f3333ddd0e423532d14edaf535',
    sizeBytes: 82468078
  },
  'whisper-base-en/preprocessor_config.json': {
    sha256: 'a6a76d28c93edb273669eb9e0b0636a2bddbb1272c3261e47b7ca6dfdbac1b8d',
    sizeBytes: 339
  },
  'whisper-base-en/tokenizer_config.json': {
    sha256: '93879c3dccdd4b976f709acd85b44778873f30c275e67026f30ca1e4c975230c',
    sizeBytes: 282662
  },
  'whisper-base-en/tokenizer.json': {
    sha256: '5eb60cec1e77aeeb6869a2bb5a8e01a84c3fe5d072d75369343021fe6f5310d0',
    sizeBytes: 2405679
  },
  'whisper-tiny-en/config.json': {
    sha256: '251ea843b5901a99efa58c0b99b8052c6019aa3e7d2baf46693a1128ff606233',
    sizeBytes: 2197
  },
  'whisper-tiny-en/generation_config.json': {
    sha256: '7b2e8451ed5f118e75fdd991409d72119d21d2fef1eba9723f68fb9c57fe5dc9',
    sizeBytes: 1646
  },
  'whisper-tiny-en/onnx/decoder_model_merged.onnx': {
    sha256: '33581ce4a48f9a59dad036a3939a24f290e0756e05387b977fe6f613460b495e',
    sizeBytes: 118552291
  },
  'whisper-tiny-en/onnx/encoder_model.onnx': {
    sha256: '8c361b9430a5ef6619ee64b7fe06c725df19f36d508cc8b847064b34a888a3fe',
    sizeBytes: 32904992
  },
  'whisper-tiny-en/preprocessor_config.json': {
    sha256: 'a6a76d28c93edb273669eb9e0b0636a2bddbb1272c3261e47b7ca6dfdbac1b8d',
    sizeBytes: 339
  },
  'whisper-tiny-en/tokenizer_config.json': {
    sha256: '93879c3dccdd4b976f709acd85b44778873f30c275e67026f30ca1e4c975230c',
    sizeBytes: 282662
  },
  'whisper-tiny-en/tokenizer.json': {
    sha256: '5eb60cec1e77aeeb6869a2bb5a8e01a84c3fe5d072d75369343021fe6f5310d0',
    sizeBytes: 2405679
  }
}
