import { createHash } from 'node:crypto'
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { CATALOG } from '../src/shared/model-catalog'

/**
 * Records what each catalog file actually is.
 *
 * Downloads every file once, hashes it, and regenerates
 * `src/shared/model-hashes.ts`. Run it whenever a catalog entry is added or an
 * upstream URL changes.
 *
 * The hashes are what make a tampered or truncated download detectable at
 * install time rather than at load time, which matters more here than usual:
 * this app puts hundreds of megabytes of model weights on other people's
 * machines and feeds them to an inference runtime.
 */

/**
 * `key` is `<entry id>/<file name>`, not the URL.
 *
 * Keying by identity means changing a URL keeps the recorded hash, so a
 * mirror or an upstream re-upload fails the checksum loudly. Keying by URL
 * would quietly drop the record and fall back to checking size alone —
 * exactly the wrong failure for the thing that exists to catch tampering.
 */
export type FileRecord = { key: string; sha256: string; sizeBytes: number }

const OUTPUT = join(__dirname, '..', 'src', 'shared', 'model-hashes.ts')

const HEADER = `/**
 * Recorded checksums and sizes for every catalog file.
 *
 * GENERATED by \`npm run verify:catalog\` — do not edit by hand. The script
 * downloads each file once and records what it actually received.
 *
 * Keyed by \`<entry id>/<file name>\` rather than by URL, so changing where a
 * file is fetched from keeps its recorded hash and fails the checksum loudly.
 * A URL key would quietly drop the record and fall back to checking size
 * alone — the wrong failure for the thing that exists to catch tampering.
 *
 * This is a generated data file rather than values inlined in the catalog so
 * that regenerating it never rewrites hand-written source, and so two entries
 * can share a file list without becoming indistinguishable to the recorder.
 */
export type ModelHash = { sha256: string; sizeBytes: number }
`

/**
 * Serialises records into the generated module.
 *
 * Sorted by URL so regenerating an unchanged catalog produces no diff, and
 * strict about empty values — a blank hash or a zero size would silently
 * disable the very checking this exists to provide.
 */
export function renderHashes(records: FileRecord[]): string {
  for (const record of records) {
    if (!record.sha256) throw new Error(`Empty hash recorded for ${record.key}`)
    if (record.sizeBytes <= 0) throw new Error(`Zero size recorded for ${record.key}`)
  }

  if (records.length === 0) {
    return `${HEADER}\nexport const MODEL_HASHES: Record<string, ModelHash> = {}\n`
  }

  // One field per line: a 64-character digest plus a key does not fit the
  // 100-column limit inline, and a generator that fights the formatter means
  // every regeneration churns the diff.
  const lines = [...records]
    .sort((a, b) => a.key.localeCompare(b.key))
    .map(
      (record) =>
        `  '${record.key}': {\n` +
        `    sha256: '${record.sha256}',\n` +
        `    sizeBytes: ${record.sizeBytes}\n` +
        `  }`
    )
    .join(',\n')

  return `${HEADER}\nexport const MODEL_HASHES: Record<string, ModelHash> = {\n${lines}\n}\n`
}

async function main(): Promise<void> {
  const records: FileRecord[] = []

  for (const entry of CATALOG) {
    for (const file of entry.files) {
      process.stdout.write(`${entry.id.padEnd(18)} ${file.name.padEnd(34)} `)

      const response = await fetch(file.url)
      if (!response.ok) throw new Error(`HTTP ${response.status} for ${file.url}`)

      const bytes = Buffer.from(await response.arrayBuffer())
      const sha256 = createHash('sha256').update(bytes).digest('hex')

      records.push({ key: `${entry.id}/${file.name}`, sha256, sizeBytes: bytes.length })
      process.stdout.write(`${String(bytes.length).padStart(10)}  ${sha256.slice(0, 12)}…\n`)
    }
  }

  await writeFile(OUTPUT, renderHashes(records), 'utf8')
  process.stdout.write(`\nRecorded ${records.length} files in src/shared/model-hashes.ts\n`)
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error)
    process.exit(1)
  })
}
